%define KB_READ_CHAR 0x00
%define KB_READ_INPUT_STATUS 0x01
%define KB_READ_SHIFT_STATUS 0x02
%define KB_STORE_KEYSTROKE_IN_BUFFER 0x05
%define KB_READ_CHAR_EXT 0x10
%define KB_READ_INPUT_STATUS_EXT 0x11
%define KB_READ_SHIFT_STATUS_EXT 0x12