; https://en.wikipedia.org/wiki/INT_10H
; https://www.ctyme.com/intr/int-10.htm
%define VIDEO_SET_MODE 0x00
%define VIDEO_SET_CURSOR_SHAPE 0x01
%define VIDEO_SET_CURSOR_POSITION 0x02
%define VIDEO_GET_CURSOR_POS_SHAPE 0x03
%define VIDEO_GET_LIGHT_PEN_POS 0x04
%define VIDEO_SET_DISPLAY_PAGE 0x05
%define VIDEO_CLR_SCROLL_UP 0x06
%define VIDEO_CLR_SCROLL_DOWN 0x07
%define VIDEO_READ_CHAR_ATTRIB 0x08
%define VIDEO_WRITE_CHAR_ATTRIB 0x09
%define VIDEO_WRITE_CHAR 0x0a
%define VIDEO_SET_BORDER_COLOUR 0x0b
%define VIDEO_WRITE_GRAPHICS_PIXEL 0x0c
%define VIDEO_READ_GRAPHICS_PIXEL 0x0d
%define VIDEO_WRITE_CHAR_TTY 0x0e
%define VIDEO_GET_MODE 0x0f
%define VIDEO_SET_PALETTE_REGS 0x10
%define VIDEO_CHARGEN 0x11
%define VIDEO_ALT_SEL 0x12
%define VIDEO_WRITE_STR 0x13
%define VIDEO_GET_SET_DISP_COMB_CODE 0x1a
%define VIDEO_GET_FUNC_INFO 0x1b
%define VIDEO_SAVE_RESTORE_VID_STATE 0x1c
%define VIDEO_VESA 0x4f

%define VESA_GET_INFO 0x4f00 ; ax