; https://en.wikipedia.org/wiki/BIOS_interrupt_call

%define INT_DIVZERO 0x00
%define INT_SINGLE_STEP 0x01
%define INT_NMI 0x02
%define INT_BREAKPOINT 0x03
%define INT_OVERFLOW 0x04
%define INT_BOUND_RANGE_EXCEEDED 0x05
%define INT_INVALID_OPCODE 0x06
%define INT_COPROC_UNAVAILABLE 0x07
%define INT_DOUBLE_FAULT 0x08
%define INT_COPROC_OVERRUN 0x09
%define INT_INVALID_TASK_STATE_SEG 0x0a
%define INT_SEG_NOT_PRESENT 0x0b
%define INT_STACK_SEGFAULT 0x0c
%define INT_GEN_PROT_FAULT 0x0d
%define INT_PAGE_FAULT 0x0e
%define INT_X87_FPE 0x10
%define INT_ALIGN_CHECK 0x11
%define INT_MACH_CHECK 0x12
%define INT_SIMD_FPE 0x13
%define INT_VIRT_EXCEPTION 0x14
%define INT_CTRL_PROT_EXCEPTION 0x15